# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='befores',
            field=models.ManyToManyField(
                related_name='afters',
                to='tasks.Task',
                blank=True,
            ),
        ),
    ]
