# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
