# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20160804_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='graph_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='graph_y',
            field=models.FloatField(null=True),
        ),
    ]
