# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20160805_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
