# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 23:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20160808_2241'),
        ('tasks', '0005_task_approved_at'),
    ]

    operations = [
    ]
