# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20160815_1856'),
        ('tasks', '0008_user_enable_keyboard_shortcuts'),
    ]

    operations = [
    ]
