# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20160811_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
